"""
Foot Slide Fix — Shelf Button Installer
=========================================

Two ways to install:

  A) DRAG this file into Maya's viewport (recommended).
  B) Paste the contents into the Script Editor (Python tab) and hit Run.

Either way the result is the same:
  - A "FootFix" button appears on your currently active shelf.
  - The button launches foot_slide_fix.py from your Maya scripts folder.
  - Drag the file in again to reinstall / replace the old button.

Make sure foot_slide_fix.py is in your Maya scripts folder:
    C:\\Users\\<you>\\Documents\\maya\\2023\\scripts\\foot_slide_fix.py
"""

import os
import base64
import maya.cmds as cmds
import maya.mel  as mel


# ============================================================================
# Constants
# ============================================================================
BUTTON_LABEL   = "FootFix"
BUTTON_TOOLTIP = "Foot Slide Fix Tool — lock foot controls to remove sliding"
ICON_FILENAME  = "foot_fix_icon.png"

# The command fired when the shelf button is clicked. scripts_dir is looked
# up at install time (below), not hard-coded, so this works on any machine.
_BUTTON_COMMAND_TEMPLATE = """# Auto-generated by Foot Slide Fix installer
import sys, importlib
scripts_dir = r"{scripts_dir}"
if scripts_dir not in sys.path:
    sys.path.insert(0, scripts_dir)
try:
    import foot_slide_fix
    importlib.reload(foot_slide_fix)
    foot_slide_fix.build_ui()
except ImportError as e:
    import maya.cmds as _cmds
    _cmds.warning("foot_slide_fix.py not found in " + scripts_dir + ": " + str(e))
"""

# ============================================================================
# Embedded 32x32 footprint icon (PNG, base64). Decoded on install.
# ============================================================================
_ICON_B64 = (
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABB0lEQVR42u1XwQqDMAyNxc/YThuy"
    "w/YD+yg9CKIUPCmCePHiXw0PXocI+w7jLpuMHdq0Fp3DQKCF9OWRvqTUulbVAAuajX0PyxJAhK0C"
    "SxrDvgeq33wfVOIpzhARKF4HAQAA1EEw7mVrilvnJJG2YcO5dokvaSq+ggERZD7FGs6F2LN0gSgH"
    "SQOnOJ5GQIBN7gLnpQOH83Etss94Ea51CEOlt+CeZaS4YxSZnwPU5G+iRudAm+fKd9/muRSXVIGu"
    "KLQF2BWFENseZngLRDkYLGzrILD3PO0EsrPMFJDuGWYaUDV2XSJ8lKXx2K0N10XgJ7qAAqxC1Nq5"
    "rvbn9FvpOsNqEoG/EOETDAwwBnNs4Z4AAAAASUVORK5CYII="
)


# ============================================================================
# Icon install — write the embedded PNG to Maya's user bitmaps folder
# ============================================================================
def install_icon():
    """Decode the embedded icon and drop it into Maya's bitmaps folder.
    Returns the absolute path to the icon on disk (or None if writing failed,
    in which case the caller falls back to a built-in Maya icon)."""
    try:
        bitmaps_dir = cmds.internalVar(userBitmapsDir=True)
        if not os.path.isdir(bitmaps_dir):
            os.makedirs(bitmaps_dir)
        icon_path = os.path.join(bitmaps_dir, ICON_FILENAME)
        with open(icon_path, "wb") as f:
            f.write(base64.b64decode(_ICON_B64))
        print("[FootFix] icon -> {}".format(icon_path))
        return icon_path.replace("\\", "/")
    except Exception as e:
        cmds.warning("[FootFix] Couldn't write icon: {}".format(e))
        return None


# ============================================================================
# Shelf button install
# ============================================================================
def create_shelf_button():
    """Add (or replace) the FootFix shelf button on the currently active shelf."""
    # 1. Figure out where foot_slide_fix.py should live — use Maya's own user
    #    scripts folder so this works on any machine, not just Sachin's.
    scripts_dir = cmds.internalVar(userScriptDir=True).rstrip("/").rstrip("\\")

    # 2. Write the icon to bitmaps so the shelf button can reference it.
    icon_path = install_icon()

    # 3. Locate the active shelf.
    top_shelf = mel.eval("$tmpShelf = $gShelfTopLevel")
    if not top_shelf or not cmds.tabLayout(top_shelf, exists=True):
        cmds.warning("[FootFix] Shelf UI not available; button not added.")
        return
    active_tab = cmds.tabLayout(top_shelf, query=True, selectTab=True)
    if not active_tab:
        cmds.warning("[FootFix] No active shelf to add the button to.")
        return

    # 4. Remove any existing FootFix button on this shelf.
    existing = cmds.shelfLayout(active_tab, q=True, childArray=True) or []
    for child in existing:
        try:
            if not cmds.shelfButton(child, exists=True):
                continue
            if cmds.shelfButton(child, q=True, label=True) == BUTTON_LABEL:
                cmds.deleteUI(child)
                print("[FootFix] removed old button: {}".format(child))
        except Exception:
            pass

    # 5. Build the command string. scripts_dir is baked in at install time.
    button_command = _BUTTON_COMMAND_TEMPLATE.format(scripts_dir=scripts_dir)

    # 6. Create the button.
    #    - Don't force width/height: Maya shelf slot is 32x32 and overriding
    #      to 64 makes the icon bleed out of the slot.
    #    - Don't set imageOverlayLabel: the custom icon already says it all,
    #      and multi-line overlays render badly at shelf size.
    if icon_path and os.path.isfile(icon_path):
        cmds.shelfButton(
            parent     = active_tab,
            label      = BUTTON_LABEL,
            command    = button_command,
            sourceType = "python",
            image      = icon_path,
            annotation = BUTTON_TOOLTIP,
        )
    else:
        # Fallback: built-in Maya icon + overlay text if icon write failed.
        cmds.shelfButton(
            parent     = active_tab,
            label      = BUTTON_LABEL,
            command    = button_command,
            sourceType = "python",
            image      = "pythonFamily.png",
            imageOverlayLabel     = "Foot",
            overlayLabelColor     = (0.95, 0.95, 0.95),
            overlayLabelBackColor = (0, 0, 0, 0.5),
            annotation = BUTTON_TOOLTIP,
        )

    # 7. Persist the shelf so the button survives a Maya restart.
    try:
        mel.eval('saveAllShelves $gShelfTopLevel;')
    except Exception:
        pass

    try:
        cmds.inViewMessage(
            amg=("<hl>FootFix installed.</hl> "
                 "Click the FootFix button on your shelf to launch."),
            pos="midCenter", fade=True, fadeStayTime=3500, dragKill=True)
    except Exception:
        pass
    print("[FootFix] button installed on shelf '{}'".format(active_tab))
    print("[FootFix] button will run foot_slide_fix.py from {}".format(scripts_dir))


# ============================================================================
# Drag-and-drop entry point
# ============================================================================
def onMayaDroppedPythonFile(obj=None):
    """Called automatically when this .py file is dragged onto the viewport."""
    create_shelf_button()


# ============================================================================
# Script Editor entry point (fallback for users who paste + Run)
# ============================================================================
# Only run on direct execution (paste-into-Script-Editor), not when Maya
# imports this module during the drag-and-drop flow.
if __name__ == "__main__":
    create_shelf_button()
